### ISSUE TITLE
hdmi不能输出4k60hz

### ISSUE THREAD

**Issue by a617282471** [yuppiesnotzhuhao/Lenovo_M920Q_Hackintosh_Bigsur_OC#1]
和作者的配置一模一样，一个dp一个HDMI，用dp可以输出4k60hz，hdmi一直输出只有4k30hz，是硬件本身限制还是什么原因，hdmi偶尔还会出现花屏现象，DP可以正确识别显示器尺寸和型号，HDMI可以识别显示器型号，尺寸就变成了61寸

**Comment by yuppiesnotzhuhao** [comment]
https://www.hacktiny.com/posts/1241.html
这里有一份M920Q的规格说明，显示其只支持HDMI1.4，而HDMI1.4不支持4K60hz。至于HDMI无法识别显示器尺寸、花屏等问题，建议尝试注入显示器的EDID，每个显示器都不一样。优先还是使用DP吧。
