### ISSUE TITLE
M920s

### ISSUE THREAD

**Issue by wqdygkd** [yuppiesnotzhuhao/Lenovo_M920Q_Hackintosh_Bigsur_OC#4]

**Comment by yuppiesnotzhuhao** [comment]
你需要告诉我你详细的硬件配置信息

**Comment by cuilongjin** [comment]
> 你需要告诉我你详细的硬件配置信息

处理器(CPU)  英特尔 Core i5-8500 @ 3.00GHz 六核    
主  板  联想 3133（Q370 芯片组）    
内  存  16 GB ( 三星 DDR4 2666MHz / 联想 DDR4 2400MHz )    
硬  盘  三星 MZVLB256HBHQ-000L7 ( 256 GB / 固态硬盘 )    
显  卡  英特尔 UHD Graphics 630 ( 128 MB / 联想 )

非常感谢

**Comment by cuilongjin** [comment]
> 你需要告诉我你详细的硬件配置信息

完整的 

  电脑型号               联想 ThinkCentre M920s-N000 台式电脑
  处理器                 英特尔 Core i5-8500 @ 3.00GHz 六核
  主板                   联想 3133（Q370 芯片组）
  显卡                   英特尔 UHD Graphics 630 ( 128 MB / 联想 )
  内存                   16 GB ( 三星 DDR4 2666MHz / 联想 DDR4 2400MHz )
  主硬盘                 三星 MZVLB256HBHQ-000L7 ( 256 GB / 固态硬盘 )
  声卡                   瑞昱 ALC662 @ 英特尔 High Definition Audio 控制器
  网卡                   英特尔 Ethernet Connection  I219-LM / 联想
  主板型号               联想 3133
  芯片组                 Q370 芯片组
  主板版本               NOK
  BIOS                   联想 M1UKT45A 
  BIOS的大小             12288 KB

多谢大佬

**Comment by yuppiesnotzhuhao** [comment]
> > 你需要告诉我你详细的硬件配置信息
> 
> 完整的
> 
> 电脑型号 联想 ThinkCentre M920s-N000 台式电脑
> 处理器 英特尔 Core i5-8500 @ 3.00GHz 六核
> 主板 联想 3133（Q370 芯片组）
> 显卡 英特尔 UHD Graphics 630 ( 128 MB / 联想 )
> 内存 16 GB ( 三星 DDR4 2666MHz / 联想 DDR4 2400MHz )
> 主硬盘 三星 MZVLB256HBHQ-000L7 ( 256 GB / 固态硬盘 )
> 声卡 瑞昱 ALC662 @ 英特尔 High Definition Audio 控制器
> 网卡 英特尔 Ethernet Connection I219-LM / 联想
> 主板型号 联想 3133
> 芯片组 Q370 芯片组
> 主板版本 NOK
> BIOS 联想 M1UKT45A
> BIOS的大小 12288 KB
> 
> 多谢大佬

完全不同的机型，我的EFI不能用是肯定的，我没有你的机型，无法做适配。
